### ISSUE TITLE
Consume libw2v as a static library

### ISSUE THREAD

**Issue by prantlf** [fogfish/word2vec#5]
Wouldn't it be easier instead of installing it on the system as a dynamic library? Especially when libw2v isn't supposed to be shared by a dozen other applications?

Converting the project to build a static library is simple:

```diff
diff --git a/libw2v/src/CMakeLists.txt b/libw2v/src/CMakeLists.txt
index 83e9c93..7f73c27 100644
--- a/libw2v/src/CMakeLists.txt
+++ b/libw2v/src/CMakeLists.txt
@@ -37,7 +37,7 @@ set(PRJ_SRCS
         ${ADD_SRCS}
         )

-add_library(${PROJECT_NAME} SHARED ${PRJ_SRCS})
+add_library(${PROJECT_NAME} STATIC ${PRJ_SRCS})
 target_link_libraries(${PROJECT_NAME} ${LIBS})
```

And `w2v/w2v` will be built with the static library.

But how to distribute it to projects depending on the `word2vec` module and for all platforms?

**Comment by prantlf** [comment]
I tried to convert the project in the [static-lib branch in my fork](https://github.com/prantlf/go-word2vec/tree/static-lib). It builds `w2v/w2v` fine by running `make`. But depending on it needs people to build the static library, so no improvement here yet. It's possible to avoid installing the library globally by cloning `word2vec` and building the library there only, for the price of forcing the local clone as a dependency:

This can be executed in a module directory, which depends on `word2vec`:
    
    # clone the word2vec project for building purposes
    git clone --depth=1 --branch=v0.0.1 https://github.com/prantlf/go-word2vec.git ../go-word2vec
    # build the static library in the local directory
    cd ../go-word2vec && make
    # replace the dependency to the directory with the static library
    go mod edit -replace github.com/fogfish/word2vec=../go-word2vec

And now you're ready to build the project and link it with `word2vec` and `libw2v` statically.

**Comment by fogfish** [comment]
Thank you for the hint and possible solution on static lib. I'd really prefer source-code distribution than any libs to multiple platform. I'll test this approach with few of my projects.

**Comment by fogfish** [comment]
Yes, this approach works. It can be also used within other apps that includes word2vec.

Usage of Github Action would be simples solution to make cross platform builds of libw2v. Once this is done the distribution becomes easy.

**Comment by fogfish** [comment]
@prantlf  Thank you for contribution! Following your advice the library is patched + static library is shipped as part of release.
